import type { NormalizedArchitecture } from '@/types/compiler';

export function synthesizeLambdaCode(normArch: NormalizedArchitecture): string {
  const { lambda, dynamodb } = normArch;
  const pk = dynamodb.partitionKey;

  return `// Generated by NapkinCloud Deterministic Compiler
// Pattern: API Gateway -> Lambda -> DynamoDB
// Runtime: ${lambda.runtime}

const { DynamoDBClient } = require("@aws-sdk/client-dynamodb");
const { DynamoDBDocumentClient, PutCommand, ScanCommand } = require("@aws-sdk/lib-dynamodb");
const crypto = require("crypto");

const client = new DynamoDBClient({});
const docClient = DynamoDBDocumentClient.from(client);
const TABLE_NAME = process.env.TABLE_NAME;

exports.handler = async (event) => {
  console.log("[NapkinCloud] Inbound Event:", JSON.stringify(event, null, 2));

  const headers = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Content-Type,X-Amz-Date,Authorization,X-Api-Key",
    "Access-Control-Allow-Methods": "OPTIONS,POST,GET,PUT,DELETE",
    "Content-Type": "application/json"
  };

  if (event.requestContext && event.requestContext.http && event.requestContext.http.method === "OPTIONS") {
    return { statusCode: 200, headers, body: JSON.stringify({ message: "OK" }) };
  }

  try {
    let body = {};
    if (event.body) {
      body = typeof event.body === "string" ? JSON.parse(event.body) : event.body;
    }

    // Auto-generate partition key if not provided by caller
    if (!body["${pk}"]) {
      body["${pk}"] = "ord-" + crypto.randomUUID().slice(0, 8);
    }

    // Injected AI Business Logic: ${lambda.businessLogicSummary.replace(/\n/g, ' ')}
    const record = {
      ...body,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      _status: "ACTIVE"
    };

    console.log("[NapkinCloud] Storing record into DynamoDB:", record);

    const putCommand = new PutCommand({
      TableName: TABLE_NAME,
      Item: record
    });

    await docClient.send(putCommand);

    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({
        success: true,
        message: "Record successfully processed and persisted in DynamoDB.",
        item: record
      })
    };
  } catch (error) {
    console.error("[NapkinCloud] Lambda Execution Error:", error);
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({
        success: false,
        error: error.message || "Internal Server Error"
      })
    };
  }
};
`;
}
