function generateLambdaCode(lambdaNode, databaseNode) {
  const functionName = lambdaNode.config?.functionName || "NapkinCloudFunction";

  const logic = lambdaNode.config?.logic || "Process the incoming request";

  const tableName = databaseNode?.config?.tableName || "NapkinCloudTable";

  const partitionKey = databaseNode?.config?.partitionKey || "id";

  return `const {
  DynamoDBClient
} = require("@aws-sdk/client-dynamodb");

const {
  DynamoDBDocumentClient,
  PutCommand
} = require("@aws-sdk/lib-dynamodb");

const {
  randomUUID
} = require("crypto");

const client = new DynamoDBClient({});

const dynamodb =
  DynamoDBDocumentClient.from(client);

exports.handler = async (event) => {
  try {
    const body =
      JSON.parse(event.body || "{}");

    // Generated by NapkinCloud
    // Function: ${functionName}
    // Logic: ${logic}

    if (!body.item || !body.qty) {
      return {
        statusCode: 400,
        body: JSON.stringify({
          error: "item and qty are required"
        })
      };
    }

    const ${partitionKey} = randomUUID();

    await dynamodb.send(
      new PutCommand({
        TableName: process.env.TABLE_NAME,

        Item: {
          ${partitionKey},
          item: body.item,
          qty: Number(body.qty),
          status: "created"
        }
      })
    );

    return {
      statusCode: 201,

      body: JSON.stringify({
        ${partitionKey},
        status: "created"
      })
    };

  } catch (error) {
    console.error(
      "Lambda execution failed:",
      error
    );

    return {
      statusCode: 500,

      body: JSON.stringify({
        error: "Internal server error"
      })
    };
  }
};
`;
}

module.exports = {
  generateLambdaCode,
};
