function generateLambdaCode(lambdaNode, databaseNode, allNodes = []) {
  const functionName = lambdaNode.data?.functionName || lambdaNode.config?.functionName || "NapkinCloudFunction";

  const logic = lambdaNode.data?.businessLogic || lambdaNode.config?.logic || "Process the incoming request";

  const tableName = databaseNode?.data?.tableName || databaseNode?.config?.tableName || "NapkinCloudTable";

  const partitionKey = databaseNode?.data?.primaryKey || databaseNode?.config?.partitionKey || "id";

  const hasS3 = allNodes.some((n) => n.type === "s3");
  const hasSQS = allNodes.some((n) => n.type === "sqs");
  const hasSNS = allNodes.some((n) => n.type === "sns");
  const hasEventBridge = allNodes.some((n) => n.type === "eventbridge");
  const hasDynamoDB = allNodes.some((n) => n.type === "dynamodb");

  return `const {
  DynamoDBClient
} = require("@aws-sdk/client-dynamodb");

const {
  DynamoDBDocumentClient,
  PutCommand,
  ScanCommand,
  DeleteCommand
} = require("@aws-sdk/lib-dynamodb");

const {
  randomUUID
} = require("crypto");

${hasS3 ? 'const { S3Client, PutObjectCommand, ListObjectsV2Command } = require("@aws-sdk/client-s3");\\nconst s3 = new S3Client({});\\n' : ''}${hasSQS ? 'const { SQSClient, SendMessageCommand } = require("@aws-sdk/client-sqs");\\nconst sqs = new SQSClient({});\\n' : ''}${hasSNS ? 'const { SNSClient, PublishCommand } = require("@aws-sdk/client-sns");\\nconst sns = new SNSClient({});\\n' : ''}${hasEventBridge ? 'const { EventBridgeClient, PutEventsCommand } = require("@aws-sdk/client-eventbridge");\\nconst eventbridge = new EventBridgeClient({});\\n' : ''}const client = new DynamoDBClient({});

const dynamodb =
  DynamoDBDocumentClient.from(client);

exports.handler = async (event) => {
  const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Content-Type,X-Amz-Date,Authorization,X-Api-Key",
    "Access-Control-Allow-Methods": "*"
  };

  const httpMethod = (event.httpMethod || (event.requestContext && event.requestContext.http && event.requestContext.http.method) || "POST").toUpperCase();

  if (httpMethod === "OPTIONS") {
    return {
      statusCode: 200,
      headers: corsHeaders,
      body: ""
    };
  }

  try {
    if (httpMethod === "GET") {
      const scanResult = await dynamodb.send(
        new ScanCommand({
          TableName: process.env.TABLE_NAME,
          Limit: 50
        })
      );
      return {
        statusCode: 200,
        headers: corsHeaders,
        body: JSON.stringify({
          success: true,
          count: scanResult.Items ? scanResult.Items.length : 0,
          items: scanResult.Items || []
        })
      };
    }

    if (httpMethod === "DELETE") {
      const queryKey = event.queryStringParameters && event.queryStringParameters["${partitionKey}"];
      let bodyKey = null;
      try {
        const parsed = JSON.parse(event.body || "{}");
        bodyKey = parsed["${partitionKey}"];
      } catch (_) {}

      const targetId = queryKey || bodyKey;
      if (targetId) {
        await dynamodb.send(
          new DeleteCommand({
            TableName: process.env.TABLE_NAME,
            Key: {
              ["${partitionKey}"]: targetId
            }
          })
        );
        return {
          statusCode: 200,
          headers: corsHeaders,
          body: JSON.stringify({
            success: true,
            message: "Record deleted",
            deletedId: targetId
          })
        };
      }
    }

    const body =
      JSON.parse(event.body || "{}");

    // Generated by NapkinCloud
    // Function: ${functionName}
    // Logic: ${logic}

    const pkValue = body["${partitionKey}"] || randomUUID();
    const now = new Date().toISOString();

    const record = {
      ...body,
      ["${partitionKey}"]: pkValue,
      createdAt: now,
      updatedAt: now
    };

    ${hasDynamoDB ? `await dynamodb.send(
      new PutCommand({
        TableName: process.env.TABLE_NAME,
        Item: record
      })
    );` : ""}

    ${hasS3 ? `if (process.env.BUCKET_NAME) {
      try {
        await s3.send(new PutObjectCommand({
          Bucket: process.env.BUCKET_NAME,
          Key: "uploads/" + pkValue + ".json",
          Body: JSON.stringify(record),
          ContentType: "application/json"
        }));
        record._s3Key = "uploads/" + pkValue + ".json";
      } catch (s3Err) {
        console.warn("[NapkinCloud] S3 write warning:", s3Err.message);
      }
    }` : ""}

    ${hasSQS ? `if (process.env.QUEUE_URL) {
      try {
        await sqs.send(new SendMessageCommand({
          QueueUrl: process.env.QUEUE_URL,
          MessageBody: JSON.stringify(record)
        }));
      } catch (sqsErr) {
        console.warn("[NapkinCloud] SQS send warning:", sqsErr.message);
      }
    }` : ""}

    ${hasSNS ? `if (process.env.TOPIC_ARN) {
      try {
        await sns.send(new PublishCommand({
          TopicArn: process.env.TOPIC_ARN,
          Message: JSON.stringify(record)
        }));
      } catch (snsErr) {
        console.warn("[NapkinCloud] SNS publish warning:", snsErr.message);
      }
    }` : ""}

    ${hasEventBridge ? `if (process.env.EVENT_BUS_NAME) {
      try {
        await eventbridge.send(new PutEventsCommand({
          Entries: [{
            EventBusName: process.env.EVENT_BUS_NAME,
            Source: "napkincloud.app",
            DetailType: "RecordCreated",
            Detail: JSON.stringify(record)
          }]
        }));
      } catch (ebErr) {
        console.warn("[NapkinCloud] EventBridge warning:", ebErr.message);
      }
    }` : ""}

    return {
      statusCode: 201,
      headers: corsHeaders,
      body: JSON.stringify(record)
    };

  } catch (error) {
    console.error(
      "Lambda execution failed:",
      error
    );

    return {
      statusCode: 500,
      headers: corsHeaders,
      body: JSON.stringify({
        error: error.message || "Internal server error"
      })
    };
  }
};
`;
}

module.exports = {
  generateLambdaCode,
};
