const { validateGraph } = require("./validator");

function generateSamTemplate(graph) {
  const validation = validateGraph(graph);
  if (!validation.valid) {
    throw new Error(`Invalid architecture:\n${validation.errors.join("\n")}`);
  }

  const api = graph.nodes.find((node) => node.type === "api_gateway");
  const lambda = graph.nodes.find((node) => node.type === "lambda");

  if (!api || !lambda) {
    throw new Error("Architecture requires at least an API Gateway entry point and a Lambda compute node.");
  }

  const database = graph.nodes.find((node) => node.type === "dynamodb");
  const s3Node = graph.nodes.find((node) => node.type === "s3");
  const sqsNode = graph.nodes.find((node) => node.type === "sqs");
  const snsNode = graph.nodes.find((node) => node.type === "sns");
  const eventBridgeNode = graph.nodes.find((node) => node.type === "eventbridge");
  const cognitoNode = graph.nodes.find((node) => node.type === "cognito");
  const secretsNode = graph.nodes.find((node) => node.type === "secrets_manager");
  const kinesisNode = graph.nodes.find((node) => node.type === "kinesis");
  const sfnNode = graph.nodes.find((node) => node.type === "step_functions");
  const cwNode = graph.nodes.find((node) => node.type === "cloudwatch");

  const method = (api.data?.method || api.config?.method || "POST").toLowerCase();
  const path = api.data?.path || api.config?.path || "/orders";
  const functionName = lambda.data?.functionName || lambda.config?.functionName || "NapkinCloudFunction";
  const partitionKey = database?.data?.primaryKey || database?.config?.partitionKey || "id";

  const template = {
    AWSTemplateFormatVersion: "2010-09-09",
    Transform: "AWS::Serverless-2016-10-31",
    Description: "Generated by NapkinCloud",
    Globals: {
      Function: {
        Runtime: "nodejs20.x",
        Timeout: 10,
      },
    },
    Resources: {
      OrdersApi: {
        Type: "AWS::Serverless::Api",
        Properties: {
          StageName: "prod",
          Cors: {
            AllowMethods: "'*'",
            AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'",
            AllowOrigin: "'*'"
          }
        },
      },
      CreateOrderFunction: {
        Type: "AWS::Serverless::Function",
        Properties: {
          FunctionName: {
            "Fn::Sub": `\${AWS::StackName}-${functionName}`,
          },
          CodeUri: {
            Bucket: "aws-sam-cli-managed-default-samclisourcebucket-67tausw1jwyw",
            Key: "placeholder/lambda.zip",
          },
          Handler: "index.handler",
          Policies: [],
          Environment: {
            Variables: {},
          },
          Events: {
            ApiEvent: {
              Type: "Api",
              Properties: {
                RestApiId: {
                  Ref: "OrdersApi",
                },
                Path: path,
                Method: method,
              },
            },
          },
        },
      },
    },
    Outputs: {
      ApiUrl: {
        Description: "Deployed API endpoint",
        Value: {
          "Fn::Sub": "https://${OrdersApi}.execute-api.${AWS::Region}.amazonaws.com/prod" + path
        }
      },
      LambdaFunctionName: {
        Description: "Deployed Lambda function",
        Value: {
          Ref: "CreateOrderFunction"
        }
      }
    }
  };

  if (database || !s3Node) {
    template.Resources.OrdersTable = {
      Type: "AWS::DynamoDB::Table",
      Properties: {
        BillingMode: "PAY_PER_REQUEST",
        AttributeDefinitions: [{ AttributeName: partitionKey, AttributeType: "S" }],
        KeySchema: [{ AttributeName: partitionKey, KeyType: "HASH" }],
      },
    };
    template.Resources.CreateOrderFunction.Properties.Policies.push({ DynamoDBCrudPolicy: { TableName: { Ref: "OrdersTable" } } });
    template.Resources.CreateOrderFunction.Properties.Environment.Variables.TABLE_NAME = { Ref: "OrdersTable" };
    template.Outputs.OrdersTableName = { Description: "Deployed DynamoDB table", Value: { Ref: "OrdersTable" } };
  }

  if (s3Node) {
    template.Resources.AppBucket = {
      Type: "AWS::S3::Bucket",
      Properties: {
        CorsConfiguration: {
          CorsRules: [
            {
              AllowedHeaders: ["*"],
              AllowedMethods: ["GET", "PUT", "POST", "HEAD", "DELETE"],
              AllowedOrigins: ["*"],
            },
          ],
        },
      },
    };
    template.Resources.CreateOrderFunction.Properties.Policies.push({ S3CrudPolicy: { BucketName: { Ref: "AppBucket" } } });
    template.Resources.CreateOrderFunction.Properties.Environment.Variables.BUCKET_NAME = { Ref: "AppBucket" };
    template.Outputs.BucketName = { Description: "Deployed S3 Bucket", Value: { Ref: "AppBucket" } };
  }

  if (sqsNode) {
    template.Resources.AppQueue = {
      Type: "AWS::SQS::Queue",
      Properties: {
        VisibilityTimeout: 30,
      },
    };
    template.Resources.CreateOrderFunction.Properties.Policies.push({ SQSSendMessagePolicy: { QueueName: { "Fn::GetAtt": ["AppQueue", "QueueName"] } } });
    template.Resources.CreateOrderFunction.Properties.Environment.Variables.QUEUE_URL = { Ref: "AppQueue" };
    template.Outputs.QueueUrl = { Description: "Deployed SQS Queue URL", Value: { Ref: "AppQueue" } };
  }

  if (snsNode) {
    template.Resources.AppTopic = { Type: "AWS::SNS::Topic" };
    template.Resources.CreateOrderFunction.Properties.Policies.push({ SNSPublishMessagePolicy: { TopicName: { "Fn::GetAtt": ["AppTopic", "TopicName"] } } });
    template.Resources.CreateOrderFunction.Properties.Environment.Variables.TOPIC_ARN = { Ref: "AppTopic" };
    template.Outputs.TopicArn = { Description: "Deployed SNS Topic ARN", Value: { Ref: "AppTopic" } };
  }

  if (eventBridgeNode) {
    template.Resources.AppEventBus = {
      Type: "AWS::Events::EventBus",
      Properties: { Name: { "Fn::Sub": "${AWS::StackName}-eventbus" } }
    };
    template.Resources.CreateOrderFunction.Properties.Policies.push({ EventBridgePutEventsPolicy: { EventBusName: { Ref: "AppEventBus" } } });
    template.Resources.CreateOrderFunction.Properties.Environment.Variables.EVENT_BUS_NAME = { Ref: "AppEventBus" };
    template.Outputs.EventBusName = { Description: "Deployed EventBridge Bus", Value: { Ref: "AppEventBus" } };
  }

  if (cognitoNode) {
    template.Resources.AppUserPool = {
      Type: "AWS::Cognito::UserPool",
      Properties: { UserPoolName: { "Fn::Sub": "${AWS::StackName}-userpool" } }
    };
    template.Resources.CreateOrderFunction.Properties.Environment.Variables.USER_POOL_ID = { Ref: "AppUserPool" };
    template.Outputs.UserPoolId = { Description: "Deployed Cognito User Pool ID", Value: { Ref: "AppUserPool" } };
  }

  if (secretsNode) {
    template.Resources.AppSecret = {
      Type: "AWS::SecretsManager::Secret",
      Properties: { Description: "Generated secret for NapkinCloud application" }
    };
    template.Resources.CreateOrderFunction.Properties.Policies.push({ SecretsManagerReadWritePolicy: { SecretArn: { Ref: "AppSecret" } } });
    template.Resources.CreateOrderFunction.Properties.Environment.Variables.SECRET_ARN = { Ref: "AppSecret" };
    template.Outputs.SecretArn = { Description: "Deployed Secret ARN", Value: { Ref: "AppSecret" } };
  }

  if (kinesisNode) {
    template.Resources.AppStream = {
      Type: "AWS::Kinesis::Stream",
      Properties: { ShardCount: 1 }
    };
    template.Resources.CreateOrderFunction.Properties.Policies.push({ KinesisCrudPolicy: { StreamName: { Ref: "AppStream" } } });
    template.Resources.CreateOrderFunction.Properties.Environment.Variables.STREAM_NAME = { Ref: "AppStream" };
    template.Outputs.StreamName = { Description: "Deployed Kinesis Stream", Value: { Ref: "AppStream" } };
  }

  if (sfnNode) {
    template.Resources.AppStateMachine = {
      Type: "AWS::Serverless::StateMachine",
      Properties: {
        Definition: {
          StartAt: "InitialState",
          States: { InitialState: { Type: "Pass", End: true } }
        },
        Policies: ["CloudWatchLogsFullAccess"]
      }
    };
    template.Resources.CreateOrderFunction.Properties.Policies.push({ StepFunctionsExecutionPolicy: { StateMachineName: { "Fn::GetAtt": ["AppStateMachine", "Name"] } } });
    template.Resources.CreateOrderFunction.Properties.Environment.Variables.STATE_MACHINE_ARN = { Ref: "AppStateMachine" };
    template.Outputs.StateMachineArn = { Description: "Deployed State Machine ARN", Value: { Ref: "AppStateMachine" } };
  }

  if (cwNode) {
    template.Resources.AppAlarm = {
      Type: "AWS::CloudWatch::Alarm",
      Properties: {
        AlarmDescription: "Alarm for Lambda errors",
        Namespace: "AWS/Lambda",
        MetricName: "Errors",
        Dimensions: [{ Name: "FunctionName", Value: { Ref: "CreateOrderFunction" } }],
        Statistic: "Sum",
        Period: 60,
        EvaluationPeriods: 1,
        Threshold: 1,
        ComparisonOperator: "GreaterThanOrEqualToThreshold"
      }
    };
    template.Outputs.AlarmName = { Description: "Deployed CloudWatch Alarm", Value: { Ref: "AppAlarm" } };
  }

  return template;
}

module.exports = {
  generateSamTemplate,
};

