const { validateGraph } = require("./validator");

function generateSamTemplate(graph) {
  const validation = validateGraph(graph);

  if (!validation.valid) {
    throw new Error(`Invalid architecture:\n${validation.errors.join("\n")}`);
  }

  const hasApi = graph.nodes.some((node) => node.type === "api_gateway");

  const hasLambda = graph.nodes.some((node) => node.type === "lambda");

  const hasDynamoDB = graph.nodes.some((node) => node.type === "dynamodb");

  if (!hasApi || !hasLambda || !hasDynamoDB) {
    throw new Error(
      "MVP compiler currently requires API Gateway → Lambda → DynamoDB",
    );
  }

  const api = graph.nodes.find((node) => node.type === "api_gateway");

  const lambda = graph.nodes.find((node) => node.type === "lambda");

  const database = graph.nodes.find((node) => node.type === "dynamodb");

  const method = api.config?.method?.toLowerCase() || "post";

  const path = api.config?.path || "/orders";

  const functionName = lambda.config?.functionName || "NapkinCloudFunction";

  const tableName = database.config?.tableName || "NapkinCloudTable";

  const partitionKey = database.config?.partitionKey || "id";

  const template = {
    AWSTemplateFormatVersion: "2010-09-09",

    Transform: "AWS::Serverless-2016-10-31",

    Description: "Generated by NapkinCloud",

    Globals: {
      Function: {
        Runtime: "nodejs22.x",
        Timeout: 10,
      },
    },

    Resources: {
      OrdersApi: {
        Type: "AWS::Serverless::Api",

        Properties: {
          StageName: "prod",
        },
      },

      OrdersTable: {
        Type: "AWS::DynamoDB::Table",

        Properties: {
          BillingMode: "PAY_PER_REQUEST",

          AttributeDefinitions: [
            {
              AttributeName: partitionKey,
              AttributeType: "S",
            },
          ],

          KeySchema: [
            {
              AttributeName: partitionKey,
              KeyType: "HASH",
            },
          ],
        },
      },

      CreateOrderFunction: {
        Type: "AWS::Serverless::Function",

        Properties: {
          FunctionName: {
            "Fn::Sub": `\${AWS::StackName}-${functionName}`,
          },

          CodeUri: {
  Bucket: "aws-sam-cli-managed-default-samclisourcebucket-67tausw1jwyw",
  Key: "placeholder/lambda.zip",
},

          Handler: "index.handler",

          Policies: [
            {
              DynamoDBCrudPolicy: {
                TableName: {
                  Ref: "OrdersTable",
                },
              },
            },
          ],

          Environment: {
            Variables: {
              TABLE_NAME: {
                Ref: "OrdersTable",
              },
            },
          },

          Events: {
            ApiEvent: {
              Type: "Api",

              Properties: {
                RestApiId: {
                  Ref: "OrdersApi",
                },

                Path: path,

                Method: method,
              },
            },
          },
        },
      },
    },
    Outputs: {
  ApiUrl: {
    Description: "Deployed API endpoint",
    Value: {
      "Fn::Sub":
        "https://${OrdersApi}.execute-api.${AWS::Region}.amazonaws.com/prod/orders"
    }
  },

  OrdersTableName: {
    Description: "Deployed DynamoDB table",
    Value: {
      Ref: "OrdersTable"
    }
  },

  LambdaFunctionName: {
    Description: "Deployed Lambda function",
    Value: {
      Ref: "CreateOrderFunction"
    }
  }
}
  };

  return template;
}

module.exports = {
  generateSamTemplate,
};
